export const tobaccoList = {
  Adalya: [
    { label: "Black cherry", value: "Black cherry" },
    { label: "Blueberry mint", value: "Blueberry mint" },
    { label: "Berry mix", value: "Berry mix" },
    { label: "Orange vanilla", value: "Orange vanilla" },
    { label: "Cinnamon", value: "Cinnamon" },
    { label: "Grape lemon", value: "Grape lemon" },
    { label: "Strawberry vanilla", value: "Strawberry vanilla" },
    { label: "Tangerine", value: "Tangerine" },
    { label: "Vanilla", value: "Vanilla" },
    { label: "Black grape", value: "Black grape" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Black mulberry", value: "Black mulberry" },
    { label: "Bluemoon", value: "Bluemoon" },
    { label: "Capuccino", value: "Capuccino" },
    { label: "Green lemon", value: "Green lemon" },
    { label: "Green lemon mint", value: "Green lemon mint" },
    { label: "Guava", value: "Guava" },
    { label: "Ice apple", value: "Ice apple" },
    { label: "Milk", value: "Milk" },
    { label: "Orange pineapple", value: "Orange pineapple" },
    { label: "Pina colada", value: "Pina colada" },
    { label: "Acai", value: "Acai" },
    { label: "Apple cinnamon", value: "Apple cinnamon" },
    { label: "Apple pie", value: "Apple pie" },
    { label: "Apricot", value: "Apricot" },
    { label: "Bahreyn apple", value: "Bahreyn apple" },
    { label: "Banana", value: "Banana" },
    { label: "Banana cinnamon", value: "Banana cinnamon" },
    { label: "Banana milk", value: "Banana milk" },
    { label: "Banana milk ice", value: "Banana milk ice" },
    { label: "Berrymix", value: "Berrymix" },
    { label: "Blackberry banana", value: "Blackberry banana" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Berlin nights", value: "Berlin nights" },
    { label: "Blue melon", value: "Blue melon" },
    { label: "Blackberry ice", value: "Blackberry ice" },
    { label: "Blue orange", value: "Blue orange" },
    { label: "Bubble gum", value: "Bubble gum" },
    { label: "Cactus", value: "Cactus" },
    { label: "Cappucino cinnamon", value: "Cappucino cinnamon" },
    { label: "Caramel", value: "Caramel" },
    { label: "Cherry banana ice", value: "Cherry banana ice" },
    { label: "Cherry banana", value: "Cherry banana" },
    { label: "Cherry ice", value: "Cherry ice" },
    { label: "Cherry mint", value: "Cherry mint" },
    { label: "Cherry pie", value: "Cherry pie" },
    { label: "Cherry", value: "Cherry" },
    { label: "Chewing gum mint cinnamon", value: "Chewing gum mint cinnamon" },
    { label: "Coconut chocolate", value: "Coconut chocolate" },
    { label: "Cranberry", value: "Cranberry" },
    { label: "Chilly cherry", value: "Chilly cherry" },
    { label: "Chocolate", value: "Chocolate" },
    { label: "Cinnamon cherry", value: "Cinnamon cherry" },
    { label: "Coconut lemon", value: "Coconut lemon" },
    { label: "Coconut", value: "Coconut" },
    { label: "Cola dragon", value: "Cola dragon" },
    { label: "Cola ice", value: "Cola ice" },
    { label: "Cola lemon ice", value: "Cola lemon ice" },
    { label: "Cola lemon", value: "Cola lemon" },
    { label: "Cola orange", value: "Cola orange" },
    { label: "Cola", value: "Cola" },
    { label: "Crazy lemon", value: "Crazy lemon" },
    { label: "Double melon ice", value: "Double melon ice" },
    { label: "Double melon", value: "Double melon" },
    { label: "Gipsiy kings", value: "Gipsiy kings" },
    { label: "Grape lemon mint", value: "Grape lemon mint" },
    { label: "Grape", value: "Grape" },
    { label: "Grape fruit", value: "Grape fruit" },
    { label: "Green apple", value: "Green apple" },
    { label: "Grape mint", value: "Grape mint" },
    { label: "Castro island", value: "Castro island" },
    { label: "Chewing gum mint", value: "Chewing gum mint" },
    { label: "Berryeis", value: "Berryeis" },
    { label: "Guarana", value: "Guarana" },
    { label: "Guava mint", value: "Guava mint" },
    { label: "Guava raspberry", value: "Guava raspberry" },
    { label: "Gum", value: "Gum" },
    { label: "Gumnastic", value: "Gumnastic" },
    { label: "Hawaii", value: "Hawaii" },
    { label: "Hazelnut", value: "Hazelnut" },
    { label: "Honey milk", value: "Honey milk" },
    { label: "Ice bonbon", value: "Ice bonbon" },
    { label: "Ice", value: "Ice" },
    { label: "Ice milk", value: "Ice milk" },
    { label: "Ice orange", value: "Ice orange" },
    { label: "Ice coffee", value: "Ice coffee" },
    { label: "Ice gum", value: "Ice gum" },
    { label: "Ice lemon", value: "Ice lemon" },
    { label: "Ice cream", value: "Ice cream" },
    { label: "Ice pear", value: "Ice pear" },
    { label: "Ice pineapple", value: "Ice pineapple" },
    { label: "Ice raspberry", value: "Ice raspberry" },
    { label: "Ice strawberry", value: "Ice strawberry" },
    { label: "Ice tangerine", value: "Ice tangerine" },
    { label: "Ice watermelon", value: "Ice watermelon" },
    { label: "Ipanema", value: "Ipanema" },
    { label: "Kiwi", value: "Kiwi" },
    { label: "Lady killer", value: "Lady killer" },
    { label: "Lemon coctail", value: "Lemon coctail" },
    { label: "Lemon mint", value: "Lemon mint" },
    { label: "Lemon pie", value: "Lemon pie" },
    { label: "Lemon", value: "Lemon" },
    { label: "Love 66", value: "Love 66" },
    { label: "Lychee", value: "Lychee" },
    { label: "Lychee blue", value: "Lychee blue" },
    { label: "Mango orange", value: "Mango orange" },
    { label: "Mango tango ice", value: "Mango tango ice" },
    { label: "Mango", value: "Mango" },
    { label: "Mango tango", value: "Mango tango" },
    { label: "Maracuja cream", value: "Maracuja cream" },
    { label: "Maracuja", value: "Maracuja" },
    { label: "Maracuja ice", value: "Maracuja ice" },
    { label: "Maracuja mint", value: "Maracuja mint" },
    { label: "Marilyn monroe", value: "Marilyn monroe" },
    { label: "Melon mint", value: "Melon mint" },
    { label: "Milk chocolate", value: "Milk chocolate" },
    { label: "Milk cinnamon", value: "Milk cinnamon" },
    { label: "Mint cinnamon", value: "Mint cinnamon" },
    { label: "Mint", value: "Mint" },
    { label: "Mix fruit", value: "Mix fruit" },
    { label: "Orange peach", value: "Orange peach" },
    { label: "Orange vanilla", value: "Orange vanilla" },
    { label: "Orange mint", value: "Orange mint" },
    { label: "Peach mint", value: "Peach mint" },
    { label: "Peach pear", value: "Peach pear" },
    { label: "Peach", value: "Peach" },
    { label: "Pear mint", value: "Pear mint" },
    { label: "Pear", value: "Pear" },
    { label: "Pineapple banana", value: "Pineapple banana" },
    { label: "Pineapple mint", value: "Pineapple mint" },
    { label: "Pineapple pie", value: "Pineapple pie" },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Pink princess", value: "Pink princess" },
    { label: "Pomagranate", value: "Pomagranate" },
    { label: "Raspberry pie", value: "Raspberry pie" },
    { label: "Rhapsody", value: "Rhapsody" },
    { label: "Spiced chai", value: "Spiced chai" },
    { label: "Strawberry banana ice", value: "Strawberry banana ice" },
    { label: "Strawberry banana", value: "Strawberry banana" },
    { label: "Strawberry lemon", value: "Strawberry lemon" },
    { label: "Strawberry pie", value: "Strawberry pie" },
    { label: "Strawberry tangarine", value: "Strawberry tangarine" },
    { label: "Strawberry vanilla mint", value: "Strawberry vanilla mint" },
    { label: "Strawberry", value: "Strawberry" },
    { label: "Summer nights", value: "Summer nights" },
    { label: "Swiss bonbon", value: "Swiss bonbon" },
    { label: "Swiss maracuja", value: "Swiss maracuja" },
    { label: "Swiss passion", value: "Swiss passion" },
    { label: "Tangarine chocolate", value: "Tangarine chocolate" },
    { label: "Three angel", value: "Three angel" },
    { label: "Tonys destiny", value: "Tonys destiny" },
    { label: "Turkish gum", value: "Turkish gum" },
    { label: "Two apple", value: "Two apple" },
    { label: "Wateremelon", value: "Wateremelon" },
    { label: "Watermelon mint", value: "Watermelon mint" },
    { label: "White grape", value: "White grape" },
    { label: "Wind of cuba", value: "Wind of cuba" },
    { label: "Power", value: "Power" },
  ],
  "Al Fakher": [
    { label: "Amber rise", value: "Amber rise" },
    { label: "Apple", value: "Apple" },
    { label: "Apricot", value: "Apricot" },
    { label: "Banana", value: "Banana" },
    { label: "Basil blast", value: "Basil blast" },
    { label: "Berry", value: "Berry" },
    { label: "Big blue", value: "Big blue" },
    { label: "Big green", value: "Big green" },
    { label: "Big blue swirls", value: "Big blue swirls" },
    { label: "Big yellow green", value: "Big yellow green" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Blueberry with mint", value: "Blueberry with mint" },
    { label: "Cappuccino", value: "Cappuccino" },
    { label: "Cardamom", value: "Cardamom" },
    { label: "Cherry", value: "Cherry" },
    { label: "Chu", value: "Chu" },
    { label: "Cinnamon", value: "Cinnamon" },
    { label: "Citrus with mint", value: "Citrus with mint" },
    { label: "Cocktail", value: "Cocktail" },
    { label: "Coconut", value: "Coconut" },
    { label: "Cool menthol", value: "Cool menthol" },
    { label: "Energy drink", value: "Energy drink" },
    { label: "Fierce fruit", value: "Fierce fruit" },
    { label: "Fresh....!", value: "Fresh....!" },
    { label: "Frost double crunch", value: "Frost double crunch" },
    { label: "Frosty two apples", value: "Frosty two apples" },
    { label: "Grape", value: "Grape" },
    { label: "Grape with cream", value: "Grape with cream" },
    { label: "Grape with mint", value: "Grape with mint" },
    { label: "Grape with berry", value: "Grape with berry" },
    { label: "Grapefruit", value: "Grapefruit" },
    { label: "Grapefruit with mint", value: "Grapefruit with mint" },
    { label: "Grapes with berry", value: "Grapes with berry" },
    { label: "Grapio", value: "Grapio" },
    { label: "Grapio green", value: "Grapio green" },
    { label: "Green chu", value: "Green chu" },
    { label: "Green velvet", value: "Green velvet" },
    { label: "Grenadine", value: "Grenadine" },
    { label: "Guava", value: "Guava" },
    { label: "Gum", value: "Gum" },
    { label: "Gum cardamom", value: "Gum cardamom" },
    { label: "Gum mastic", value: "Gum mastic" },
    { label: "Gum with cinnamon", value: "Gum with cinnamon" },
    { label: "Gum with mint", value: "Gum with mint" },
    { label: "Gum with cardamom", value: "Gum with cardamom" },
    { label: "Iced gum", value: "Iced gum" },
    { label: "Iced lemon with mint", value: "Iced lemon with mint" },
    { label: "Iced raspberry mint", value: "Iced raspberry mint" },
    { label: "Ivory gold", value: "Ivory gold" },
    { label: "Kiwi", value: "Kiwi" },
    { label: "Lemon", value: "Lemon" },
    { label: "Lemon with mint", value: "Lemon with mint" },
    { label: "Magic love", value: "Magic love" },
    { label: "Mango", value: "Mango" },
    { label: "Mango kiwi", value: "Mango kiwi" },
    { label: "Melon", value: "Melon" },
    { label: "Mint", value: "Mint" },
    { label: "Mint frost", value: "Mint frost" },
    { label: "Mint with cream", value: "Mint with cream" },
    { label: "Minty fresh", value: "Minty fresh" },
    { label: "Mojito", value: "Mojito" },
    { label: "Ocean", value: "Ocean" },
    { label: "Orange", value: "Orange" },
    { label: "Orange with cream", value: "Orange with cream" },
    { label: "Orange with mint", value: "Orange with mint" },
    { label: "Peach", value: "Peach" },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Plum", value: "Plum" },
    { label: "Polar freeze", value: "Polar freeze" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Red green smash", value: "Red green smash" },
    { label: "Red smash", value: "Red smash" },
    { label: "Rose", value: "Rose" },
    { label: "Smooth cream", value: "Smooth cream" },
    { label: "Snowy chu", value: "Snowy chu" },
    { label: "Snowy fuchsia green", value: "Snowy fuchsia green" },
    { label: "Sour power", value: "Sour power" },
    { label: "Strawberry", value: "Strawberry" },
    { label: "Strawberry with cream", value: "Strawberry with cream" },
    { label: "Sub zero", value: "Sub zero" },
    { label: "Super lemon mint", value: "Super lemon mint" },
    { label: "Sweet passion fruit", value: "Sweet passion fruit" },
    { label: "The double crunch", value: "The double crunch" },
    { label: "Twist", value: "Twist" },
    { label: "Two apple bahraini", value: "Two apple bahraini" },
    { label: "Two apple cardamom", value: "Two apple cardamom" },
    { label: "Two apples", value: "Two apples" },
    { label: "Two apples with mint", value: "Two apples with mint" },
    { label: "Vanilla", value: "Vanilla" },
    { label: "Watermelon", value: "Watermelon" },
    { label: "Watermelon with mint", value: "Watermelon with mint" },
    { label: "White flash", value: "White flash" },
    { label: "Wicked emerald", value: "Wicked emerald" },
    { label: "Апельсин", value: "Апельсин" },
    { label: "Арбуз", value: "Арбуз" },
    { label: "Банан", value: "Банан" },
    { label: "Белое золото", value: "Белое золото" },
    { label: "Ваниль", value: "Ваниль" },
    { label: "Виноград", value: "Виноград" },
    { label: "Вишня", value: "Вишня" },
    { label: "Гранат", value: "Гранат" },
    { label: "Грейпфрут", value: "Грейпфрут" },
    { label: "Два яблока", value: "Два яблока" },
    { label: "Дыня", value: "Дыня" },
    { label: "Жвательная резинка", value: "Жвательная резинка" },
    { label: "Киви", value: "Киви" },
    { label: "Клубника", value: "Клубника" },
    { label: "Кокос", value: "Кокос" },
    { label: "Коктейль", value: "Коктейль" },
    { label: "Манго", value: "Манго" },
    { label: "Мята", value: "Мята" },
    { label: "Персик", value: "Персик" },
    { label: "Свежесть…!", value: "Свежесть…!" },
    { label: "Супер лимон - мята", value: "Супер лимон - мята" },
    { label: "Чай эрл грей", value: "Чай эрл грей" },
    { label: "Черника", value: "Черника" },
    { label: "Ягоды", value: "Ягоды" },
    { label: "Янтарный восход", value: "Янтарный восход" },
  ],
  "Azure Gold": [
    { label: "Apple cider ", value: "Apple cider " },
    { label: "Baristas choice ", value: "Baristas choice " },
    { label: "Bermuda mint ", value: "Bermuda mint " },
    { label: "Berrymania ", value: "Berrymania " },
    { label: "Blueberry muffin ", value: "Blueberry muffin " },
    { label: "Bomerang ", value: "Bomerang " },
    { label: "Cairo crypt tonight ", value: "Cairo crypt tonight " },
    { label: "California blue ", value: "California blue " },
    { label: "Candy ", value: "Candy " },
    { label: "Carolina peach ", value: "Carolina peach " },
    { label: "Chai masala ", value: "Chai masala " },
    { label: "Cherry muffin ", value: "Cherry muffin " },
    { label: "Chocolate cake ", value: "Chocolate cake " },
    { label: "Chocolate mint ", value: "Chocolate mint " },
    { label: "Cinnamon cookie ", value: "Cinnamon cookie " },
    { label: "Citrusmania ", value: "Citrusmania " },
    { label: "Cocomania ", value: "Cocomania " },
    { label: "Cosmos black", value: "Cosmos black" },
    { label: "Dubai apple ", value: "Dubai apple " },
    { label: "Fun at the beach ", value: "Fun at the beach " },
    { label: "Grapemania ", value: "Grapemania " },
    { label: "Grow a pear ", value: "Grow a pear " },
    { label: "Lemongrass ", value: "Lemongrass " },
    { label: "Lemon muffin ", value: "Lemon muffin " },
    { label: "Limoncello ", value: "Limoncello " },
    { label: "Lychee ", value: "Lychee " },
    { label: "Mango cheesecake ", value: "Mango cheesecake " },
    { label: "Melon king ", value: "Melon king " },
    { label: "Melonmania ", value: "Melonmania " },
    { label: "Moscow never sleeps ", value: "Moscow never sleeps " },
    { label: "Napa grape ", value: "Napa grape " },
    { label: "Orange my guava black", value: "Orange my guava black" },
    { label: "Pina colada ", value: "Pina colada " },
    { label: "Rio mint ", value: "Rio mint " },
    { label: "Royal mango ", value: "Royal mango " },
    { label: "Royal queen ", value: "Royal queen " },
    { label: "Royal raspberry ", value: "Royal raspberry " },
    { label: "Spiced berry ", value: "Spiced berry " },
    { label: "Strawberry passion ", value: "Strawberry passion " },
    { label: "Strawberry guava ", value: "Strawberry guava " },
    { label: "Sweet summer sun ", value: "Sweet summer sun " },
    { label: "Tomahawk ", value: "Tomahawk " },
    { label: "Tropical citrus ", value: "Tropical citrus " },
    { label: "Tropical paradise ", value: "Tropical paradise " },
    { label: "Twisted tea ", value: "Twisted tea " },
    { label: "Unicorn ", value: "Unicorn " },
    { label: "Viva la horchata ", value: "Viva la horchata " },
    { label: "White gummi bear ", value: "White gummi bear " },
    { label: "Winter berries ", value: "Winter berries " },
    { label: "Winter lemon ", value: "Winter lemon " },
    { label: "Winter orange ", value: "Winter orange " },
    { label: "Winter peach ", value: "Winter peach " },
    { label: "Winter rose ", value: "Winter rose " },
  ],
  "Azure Black": [
    { label: "Apple cider black", value: "Apple cider black" },
    { label: "Baristas choice black", value: "Baristas choice black" },
    { label: "Bengal citrus black", value: "Bengal citrus black" },
    { label: "Bermuda mint black", value: "Bermuda mint black" },
    { label: "Berrymania black", value: "Berrymania black" },
    { label: "Blueberry black", value: "Blueberry black" },
    { label: "Blueberry muffin black", value: "Blueberry muffin black" },
    { label: "Cactus blast black", value: "Cactus blast black" },
    { label: "Cairo crypt tonight black", value: "Cairo crypt tonight black" },
    { label: "California blue black", value: "California blue black" },
    { label: "Carolina peach black", value: "Carolina peach black" },
    { label: "Chai masala black", value: "Chai masala black" },
    { label: "Cherry muffin black", value: "Cherry muffin black" },
    { label: "Chocolate cake black", value: "Chocolate cake black" },
    { label: "Chocolate mint black", value: "Chocolate mint black" },
    { label: "Cinnamon cookie black", value: "Cinnamon cookie black" },
    { label: "Citrusmania black", value: "Citrusmania black" },
    { label: "Cocomania black", value: "Cocomania black" },
    { label: "Cola black", value: "Cola black" },
    { label: "Cosmos gold", value: "Cosmos gold" },
    { label: "Dubai apple black", value: "Dubai apple black" },
    { label: "Grapemania black", value: "Grapemania black" },
    { label: "Grow a pear black", value: "Grow a pear black" },
    { label: "Island city blend black", value: "Island city blend black" },
    { label: "Lady liberty black", value: "Lady liberty black" },
    { label: "Lemon muffin black", value: "Lemon muffin black" },
    { label: "Lemongrass black", value: "Lemongrass black" },
    { label: "Mango cheesecake black", value: "Mango cheesecake black" },
    { label: "Melon king black", value: "Melon king black" },
    { label: "Melonmania black", value: "Melonmania black" },
    { label: "Moroccan tea black", value: "Moroccan tea black" },
    { label: "Moroco mentha black", value: "Moroco mentha black" },
    { label: "Napa grape black", value: "Napa grape black" },
    { label: "Orange my guava gold", value: "Orange my guava gold" },
    { label: "Rio mint black", value: "Rio mint black" },
    { label: "Royal citrus black", value: "Royal citrus black" },
    { label: "Royal mango black", value: "Royal mango black" },
    { label: "Royal queen black", value: "Royal queen black" },
    { label: "Royal raspberry black", value: "Royal raspberry black" },
    { label: "San diego sunset black", value: "San diego sunset black" },
    { label: "Spiced berry black", value: "Spiced berry black" },
    { label: "Strawberry passion black", value: "Strawberry passion black" },
    { label: "Strawberry guava black", value: "Strawberry guava black" },
    { label: "Sweet summer sun black", value: "Sweet summer sun black" },
    { label: "Ultra violet black", value: "Ultra violet black" },
    { label: "Unicorn black", value: "Unicorn black" },
    { label: "Viva la horchata black", value: "Viva la horchata black" },
  ],
  Chaos: [
    { label: "Adios amigos", value: "Adios amigos" },
    { label: "Aloetika", value: "Aloetika" },
    { label: "Amore mio", value: "Amore mio" },
    { label: "Arabic prince", value: "Arabic prince" },
    { label: "Aschenputtel", value: "Aschenputtel" },
    { label: "Babylou", value: "Babylou" },
    { label: "Baby noah", value: "Baby noah" },
    { label: "Bubble juice", value: "Bubble juice" },
    { label: "Crayz goblin", value: "Crayz goblin" },
    { label: "Cucumbra", value: "Cucumbra" },
    { label: "Deja-vu", value: "Deja-vu" },
    { label: "Destiny", value: "Destiny" },
    { label: "Dj oldshool", value: "Dj oldshool" },
    { label: "Elektra", value: "Elektra" },
    { label: "El patron", value: "El patron" },
    { label: "Foreplay", value: "Foreplay" },
    { label: "Fristy", value: "Fristy" },
    { label: "Golden flower", value: "Golden flower" },
    { label: "Funky monkey", value: "Funky monkey" },
    { label: "Iceman", value: "Iceman" },
    { label: "Iceplosion", value: "Iceplosion" },
    { label: "Le chef", value: "Le chef" },
    { label: "Limonato", value: "Limonato" },
    { label: "Major", value: "Major" },
    { label: "Mangana", value: "Mangana" },
    { label: "Medusa", value: "Medusa" },
    { label: "Memento", value: "Memento" },
    { label: "Mephisto", value: "Mephisto" },
    { label: "Nero", value: "Nero" },
    { label: "Omg", value: "Omg" },
    { label: "Oriental cay", value: "Oriental cay" },
    { label: "Origami", value: "Origami" },
    { label: "Mr.roboto", value: "Mr.roboto" },
    { label: "Muscleman", value: "Muscleman" },
    { label: "Passionata", value: "Passionata" },
    { label: "Prince william", value: "Prince william" },
    { label: "Policeman", value: "Policeman" },
    { label: "Purple dust", value: "Purple dust" },
    { label: "Royal blend", value: "Royal blend" },
    { label: "Sensei", value: "Sensei" },
    { label: "Starboy", value: "Starboy" },
    { label: "Static poison", value: "Static poison" },
    { label: "Supernova", value: "Supernova" },
    { label: "The reaper", value: "The reaper" },
    { label: "The riddle", value: "The riddle" },
    { label: "The wave", value: "The wave" },
    { label: "Toxic", value: "Toxic" },
    { label: "Tsunami", value: "Tsunami" },
    { label: "Turkish bubble", value: "Turkish bubble" },
    { label: "Turkish bubble blue", value: "Turkish bubble blue" },
    { label: "Turkish bubble brown", value: "Turkish bubble brown" },
    { label: "Turkish bubble red", value: "Turkish bubble red" },
    { label: "Wild sheriff", value: "Wild sheriff" },
    { label: "Violino", value: "Violino" },
    { label: "Zorwans secret", value: "Zorwans secret" },
    { label: "Wtf", value: "Wtf" },
    { label: "Xoxo", value: "Xoxo" },
    { label: "Coka nostra", value: "Coka nostra" },
    { label: "Karma", value: "Karma" },
    { label: "Knockout", value: "Knockout" },
    { label: "Peanut butter", value: "Peanut butter" },
    { label: "The fusion", value: "The fusion" },
    { label: "Candy shop", value: "Candy shop" },
    { label: "Hypnotize", value: "Hypnotize" },
    { label: "Ice ice baby", value: "Ice ice baby" },
  ],
  "Darkside Base": [
    { label: "Astro tea", value: "Astro tea" },
    { label: "Blueberry blast", value: "Blueberry blast" },
    { label: "Darkside cola", value: "Darkside cola" },
    { label: "Glitch ice tea", value: "Glitch ice tea" },
    { label: "Barberry gum", value: "Barberry gum" },
    { label: "Code cherry ", value: "Code cherry " },
    { label: "Generis raspberry", value: "Generis raspberry" },
    { label: "Needls", value: "Needls" },
    { label: "Salbei ", value: "Salbei " },
    { label: "Strawberry light", value: "Strawberry light" },
    { label: "Virgin peach", value: "Virgin peach" },
    { label: "Wild forest", value: "Wild forest" },
    { label: "Bananapapa", value: "Bananapapa" },
    { label: "Bounty hunter", value: "Bounty hunter" },
    { label: "Green beam", value: "Green beam" },
    { label: "Polar cream", value: "Polar cream" },
    { label: "Barvy citrus", value: "Barvy citrus" },
    { label: "Darkside cookie", value: "Darkside cookie" },
    { label: "Gonzo cake", value: "Gonzo cake" },
    { label: "Nutz", value: "Nutz" },
    { label: "Sambuka shot", value: "Sambuka shot" },
    { label: "Supernova", value: "Supernova" },
    { label: "Wildberry", value: "Wildberry" },
    { label: "Basil blast", value: "Basil blast" },
    { label: "Cosmo flower", value: "Cosmo flower" },
    { label: "Sweet comet", value: "Sweet comet" },
    { label: "Ice granny", value: "Ice granny" },
    { label: "Barvy orange", value: "Barvy orange" },
    { label: "Eclipse", value: "Eclipse" },
    { label: "Kalee grapefruit", value: "Kalee grapefruit" },
    { label: "Pear", value: "Pear" },
    { label: "Skylime", value: "Skylime" },
    { label: "Torpedo", value: "Torpedo" },
    { label: "Cosmos", value: "Cosmos" },
    { label: "Bergamonstr", value: "Bergamonstr" },
    { label: "Dark icecream", value: "Dark icecream" },
    { label: "Falling star", value: "Falling star" },
    { label: "Admiral acbar cereal", value: "Admiral acbar cereal" },
    { label: "Blackcurrant", value: "Blackcurrant" },
    { label: "Extragon", value: "Extragon" },
    { label: "Lemonblast", value: "Lemonblast" },
    { label: "Red tea", value: "Red tea" },
    { label: "Space dessert", value: "Space dessert" },
    { label: "Tropic ray", value: "Tropic ray" },
    { label: "Dark spirit", value: "Dark spirit" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Dark mint", value: "Dark mint" },
    { label: "Grape core ", value: "Grape core " },
    { label: "Applecot", value: "Applecot" },
    { label: "Cinnamoon", value: "Cinnamoon" },
    { label: "Fruity dust", value: "Fruity dust" },
    { label: "Mango lassi", value: "Mango lassi" },
    { label: "Redberry", value: "Redberry" },
    { label: "Spicy pear", value: "Spicy pear" },
    { label: "Virgin melon", value: "Virgin melon" },
    { label: "Space lychee", value: "Space lychee" },
  ],
  "Darkside Core": [
    { label: "Astro tea", value: "Astro tea" },
    { label: "Blueberry blast", value: "Blueberry blast" },
    { label: "Darkside cola", value: "Darkside cola" },
    { label: "Glitch ice tea", value: "Glitch ice tea" },
    { label: "Barberry gum", value: "Barberry gum" },
    { label: "Code cherry ", value: "Code cherry " },
    { label: "Generis raspberry", value: "Generis raspberry" },
    { label: "Needls", value: "Needls" },
    { label: "Salbei ", value: "Salbei " },
    { label: "Strawberry light", value: "Strawberry light" },
    { label: "Virgin peach", value: "Virgin peach" },
    { label: "Red alert", value: "Red alert" },
    { label: "Bananapapa", value: "Bananapapa" },
    { label: "Bounty hunter", value: "Bounty hunter" },
    { label: "Green beam", value: "Green beam" },
    { label: "Polar cream", value: "Polar cream" },
    { label: "Barvy citrus", value: "Barvy citrus" },
    { label: "Darkside cookie", value: "Darkside cookie" },
    { label: "Gonzo cake", value: "Gonzo cake" },
    { label: "Nutz", value: "Nutz" },
    { label: "Sambuka shot", value: "Sambuka shot" },
    { label: "Supernova", value: "Supernova" },
    { label: "Wildberry", value: "Wildberry" },
    { label: "Darksupra", value: "Darksupra" },
    { label: "Basil blast", value: "Basil blast" },
    { label: "Cosmo flower", value: "Cosmo flower" },
    { label: "Sweet comet", value: "Sweet comet" },
    { label: "Ice granny", value: "Ice granny" },
    { label: "Barvy orange", value: "Barvy orange" },
    { label: "Eclipse", value: "Eclipse" },
    { label: "Kalee grapefruit", value: "Kalee grapefruit" },
    { label: "Pear", value: "Pear" },
    { label: "Skylime", value: "Skylime" },
    { label: "Torpedo", value: "Torpedo" },
    { label: "Cosmos", value: "Cosmos" },
    { label: "Guava rebel", value: "Guava rebel" },
    { label: "Bergamonstr", value: "Bergamonstr" },
    { label: "Dark icecream", value: "Dark icecream" },
    { label: "Falling star", value: "Falling star" },
    { label: "Admiral acbar cereal", value: "Admiral acbar cereal" },
    { label: "Blackcurrant", value: "Blackcurrant" },
    { label: "Extragon", value: "Extragon" },
    { label: "Lemonblast", value: "Lemonblast" },
    { label: "Red tea", value: "Red tea" },
    { label: "Space dessert", value: "Space dessert" },
    { label: "Tropic ray", value: "Tropic ray" },
    { label: "Dark spirit", value: "Dark spirit" },
    { label: "Wild forest", value: "Wild forest" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Dark mint", value: "Dark mint" },
    { label: "Grape core ", value: "Grape core " },
    { label: "Applecot", value: "Applecot" },
    { label: "Cinnamoon", value: "Cinnamoon" },
    { label: "Fruity dust", value: "Fruity dust" },
    { label: "Mango lassi", value: "Mango lassi" },
    { label: "Redberry", value: "Redberry" },
    { label: "Spicy pear", value: "Spicy pear" },
    { label: "Virgin melon", value: "Virgin melon" },
    { label: "Space lychee", value: "Space lychee" },
    { label: "Deep blue sea", value: "Deep blue sea" },
  ],
  "Darkside Rare": [
    { label: "Bananapapa", value: "Bananapapa" },
    { label: "Falling star", value: "Falling star" },
    { label: "Darkside cookie", value: "Darkside cookie" },
    { label: "Blueberry blast", value: "Blueberry blast" },
    { label: "Grape core ", value: "Grape core " },
    { label: "Extragon", value: "Extragon" },
    { label: "Darkside cola", value: "Darkside cola" },
    { label: "Glitch ice tea", value: "Glitch ice tea" },
    { label: "Green beam", value: "Green beam" },
    { label: "Polar cream", value: "Polar cream" },
    { label: "Sweet comet", value: "Sweet comet" },
    { label: "Ice granny", value: "Ice granny" },
  ],
  "Element Water": [
    { label: "Ekzo", value: "Ekzo" },
    { label: "Margarita", value: "Margarita" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Wildberry mors", value: "Wildberry mors" },
    { label: "Peach", value: "Peach" },
    { label: "Feijoa", value: "Feijoa" },
    { label: "Thyme&bergamot", value: "Thyme&bergamot" },
    { label: "Currant", value: "Currant" },
    { label: "Fir", value: "Fir" },
    { label: "Moroz", value: "Moroz" },
    { label: "Grape mint", value: "Grape mint" },
    { label: "Nuts mix", value: "Nuts mix" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Cola", value: "Cola" },
    { label: "Mango", value: "Mango" },
    { label: "Lychee", value: "Lychee" },
    { label: "Cookie monster ", value: "Cookie monster " },
    { label: "Lemon", value: "Lemon" },
    { label: "Kalamansi", value: "Kalamansi" },
    { label: "Cactus fig", value: "Cactus fig" },
    { label: "Pomegranate", value: "Pomegranate" },
    { label: "Pear", value: "Pear" },
    { label: "Cherry ", value: "Cherry " },
    { label: "Basil ", value: "Basil " },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Banana daikiri ", value: "Banana daikiri " },
    { label: "Pomelo-grapefruit", value: "Pomelo-grapefruit" },
    { label: "Belgien waffle", value: "Belgien waffle" },
    { label: "Watermelon holls", value: "Watermelon holls" },
    { label: "Lemongrass", value: "Lemongrass" },
  ],
  "Element Earth": [
    { label: "Ekzo", value: "Ekzo" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Feijoa", value: "Feijoa" },
    { label: "Currant", value: "Currant" },
    { label: "Fir", value: "Fir" },
    { label: "Peach ", value: "Peach " },
    { label: "Grape mint", value: "Grape mint" },
    { label: "Margarita", value: "Margarita" },
    { label: "Mango", value: "Mango" },
    { label: "Lychee", value: "Lychee" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Cola", value: "Cola" },
    { label: "Kashmir", value: "Kashmir" },
    { label: "Cactus fig", value: "Cactus fig" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Irish cream", value: "Irish cream" },
    { label: "Lemongrass", value: "Lemongrass" },
    { label: "Kashmir feijoa ", value: "Kashmir feijoa " },
    { label: "Pear", value: "Pear" },
    { label: "Pomelo grapefruit", value: "Pomelo grapefruit" },
    { label: "Banana daikiri ", value: "Banana daikiri " },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Cherry ", value: "Cherry " },
  ],
  "Element Air": [
    { label: "Ekzo", value: "Ekzo" },
    { label: "Fruitberry", value: "Fruitberry" },
    { label: "Tamarind", value: "Tamarind" },
    { label: "Thai mango", value: "Thai mango" },
    { label: "Grape mint", value: "Grape mint" },
    { label: "Orchata", value: "Orchata" },
    { label: "Li-ci", value: "Li-ci" },
    { label: "Margarita", value: "Margarita" },
    { label: "Lemongrass", value: "Lemongrass" },
    { label: "Berrytale", value: "Berrytale" },
    { label: "Noirmelon", value: "Noirmelon" },
    { label: "Amazingreen", value: "Amazingreen" },
    { label: "Melon holls", value: "Melon holls" },
    { label: "Garnet holls", value: "Garnet holls" },
    { label: "Bananerro", value: "Bananerro" },
    { label: "Berrymore", value: "Berrymore" },
    { label: "Buzina", value: "Buzina" },
    { label: "Bellini", value: "Bellini" },
    { label: "Baikal", value: "Baikal" },
    { label: "Maui", value: "Maui" },
  ],
  Fumari: [
    { label: "Aloha mango", value: "Aloha mango" },
    { label: "Ambrosia", value: "Ambrosia" },
    { label: "Banana custard", value: "Banana custard" },
    { label: "Blueberry muffin", value: "Blueberry muffin" },
    { label: "Caribbean colada", value: "Caribbean colada" },
    { label: "Citrus mint", value: "Citrus mint" },
    { label: "Citrus tea", value: "Citrus tea" },
    { label: "Double apple", value: "Double apple" },
    { label: "French vanilla", value: "French vanilla" },
    { label: "Guava", value: "Guava" },
    { label: "Island papaya", value: "Island papaya" },
    { label: "Lemon loaf", value: "Lemon loaf" },
    { label: "Lemon mint", value: "Lemon mint" },
    { label: "Limoncello", value: "Limoncello" },
    { label: "Mandarin zest", value: "Mandarin zest" },
    { label: "Mint", value: "Mint" },
    { label: "Mint chocolate chill", value: "Mint chocolate chill" },
    { label: "Mochaccino", value: "Mochaccino" },
    { label: "Mojito mojo", value: "Mojito mojo" },
    { label: "Nectarine", value: "Nectarine" },
    { label: "Orange cream", value: "Orange cream" },
    { label: "Prickly pear", value: "Prickly pear" },
    { label: "Purple grape", value: "Purple grape" },
    { label: "Rgb", value: "Rgb" },
    { label: "Sour cherry", value: "Sour cherry" },
    { label: "Spiced chai", value: "Spiced chai" },
    { label: "Summer sorbetto", value: "Summer sorbetto" },
    { label: "Sweet mint", value: "Sweet mint" },
    { label: "Tangelo", value: "Tangelo" },
    { label: "Tropical punch", value: "Tropical punch" },
    { label: "Watermelon", value: "Watermelon" },
    { label: "Wgb", value: "Wgb" },
    { label: "White peach", value: "White peach" },
  ],
  Holster: [
    { label: "Grp 2.0", value: "Grp 2.0" },
    { label: "!ce kaktuz", value: "!ce kaktuz" },
    { label: "Quwipunch", value: "Quwipunch" },
    { label: "Bloody punch", value: "Bloody punch" },
    { label: "Bono", value: "Bono" },
    { label: "Mr.john", value: "Mr.john" },
    { label: "Smurf daddy", value: "Smurf daddy" },
    { label: "!ce bomb", value: "!ce bomb" },
    { label: "Miss joosy", value: "Miss joosy" },
    { label: "Watermillpunch", value: "Watermillpunch" },
    { label: "Wildpunch", value: "Wildpunch" },
    { label: "Booster", value: "Booster" },
    { label: "Limited edition (special)", value: "Limited edition (special)" },
  ],
  MustHave: [
    { label: "Pinkman", value: "Pinkman" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Orange team", value: "Orange team" },
    { label: "Pineapple rings", value: "Pineapple rings" },
    { label: "Mango sling", value: "Mango sling" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Berry holls", value: "Berry holls" },
    { label: "Ruby grape", value: "Ruby grape" },
    { label: "Black currant", value: "Black currant" },
    { label: "Space flavour", value: "Space flavour" },
    { label: "Melonade", value: "Melonade" },
    { label: "Cherry-cola", value: "Cherry-cola" },
    { label: "Forest berries", value: "Forest berries" },
    { label: "Banana mama", value: "Banana mama" },
    { label: "Morocco", value: "Morocco" },
    { label: "Estragon", value: "Estragon" },
    { label: "Grapefruit", value: "Grapefruit" },
    { label: "Cranberry", value: "Cranberry" },
    { label: "Nord star", value: "Nord star" },
    { label: "Barberry candy", value: "Barberry candy" },
    { label: "Masala tea", value: "Masala tea" },
    { label: "Unicorn treats", value: "Unicorn treats" },
    { label: "Sweet peach", value: "Sweet peach" },
    { label: "Lemon-lime", value: "Lemon-lime" },
    { label: "Cinnamon", value: "Cinnamon" },
    { label: "Peppermint", value: "Peppermint" },
    { label: "Sweet melon", value: "Sweet melon" },
    { label: "Strawberry-lychee", value: "Strawberry-lychee" },
    { label: "Cookie", value: "Cookie" },
    { label: "Choco-mint", value: "Choco-mint" },
    { label: "Marula", value: "Marula" },
    { label: "Apple drops", value: "Apple drops" },
    { label: "Pistachio", value: "Pistachio" },
    { label: "Ice mint", value: "Ice mint" },
    { label: "Mulled wine", value: "Mulled wine" },
    { label: "Kiwi smoothie", value: "Kiwi smoothie" },
    { label: "Red bomb", value: "Red bomb" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Pistachio cake", value: "Pistachio cake" },
    { label: "Mad pear", value: "Mad pear" },
    { label: "Tropic juice", value: "Tropic juice" },
    { label: "Feijoa", value: "Feijoa" },
    { label: "Frosty", value: "Frosty" },
    { label: "Milky rice", value: "Milky rice" },
    { label: "Coconut shake", value: "Coconut shake" },
    { label: "Sea buckthorn tea", value: "Sea buckthorn tea" },
    { label: "Quince", value: "Quince" },
    { label: "Baikal", value: "Baikal" },
    { label: "Lemon pie", value: "Lemon pie" },
    { label: "Candy cow", value: "Candy cow" },
    { label: "Christmas drink", value: "Christmas drink" },
    { label: "Honey holls", value: "Honey holls" },
    { label: "Rocket", value: "Rocket" },
  ],
  Starbuzz: [
    { label: "Apple cinnamon", value: "Apple cinnamon" },
    { label: "Apple martini", value: "Apple martini" },
    { label: "Arabian coffee", value: "Arabian coffee" },
    { label: "Banana", value: "Banana" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Black grape", value: "Black grape" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Blueberry grape", value: "Blueberry grape" },
    { label: "Blue mist", value: "Blue mist" },
    { label: "Blue surfer", value: "Blue surfer" },
    { label: "Bubble gum", value: "Bubble gum" },
    { label: "Candy", value: "Candy" },
    { label: "Cantaloupe", value: "Cantaloupe" },
    { label: "Cappuccino", value: "Cappuccino" },
    { label: "Caramel apple", value: "Caramel apple" },
    { label: "Caramel macchiato", value: "Caramel macchiato" },
    { label: "Cherry", value: "Cherry" },
    { label: "Christmas mix", value: "Christmas mix" },
    { label: "Chocolate mint", value: "Chocolate mint" },
    { label: "Chocolate strawberry", value: "Chocolate strawberry" },
    { label: "Citrus mint", value: "Citrus mint" },
    { label: "Citrus mist", value: "Citrus mist" },
    { label: "Classic cola", value: "Classic cola" },
    { label: "Classic mojito", value: "Classic mojito" },
    { label: "Coco jumbo", value: "Coco jumbo" },
    { label: "Coconut", value: "Coconut" },
    { label: "Code ", value: "Code " },
    { label: "Cosmopolitan", value: "Cosmopolitan" },
    { label: "Cotton candy", value: "Cotton candy" },
    { label: "Double apple", value: "Double apple" },
    { label: "Egyptian pharos", value: "Egyptian pharos" },
    { label: "Exotic grape", value: "Exotic grape" },
    { label: "Flower power", value: "Flower power" },
    { label: "Fruit sensation", value: "Fruit sensation" },
    { label: "Fuzzy lemonade", value: "Fuzzy lemonade" },
    { label: "Fuzzy naval", value: "Fuzzy naval" },
    { label: "Grapefruit", value: "Grapefruit" },
    { label: "Guava", value: "Guava" },
    { label: "Hard rush", value: "Hard rush" },
    { label: "Holiday mix", value: "Holiday mix" },
    { label: "Honey berry", value: "Honey berry" },
    { label: "Jasmine", value: "Jasmine" },
    { label: "Kiwi", value: "Kiwi" },
    { label: "Kiwi strawberry", value: "Kiwi strawberry" },
    { label: "Lebanese bombshell", value: "Lebanese bombshell" },
    { label: "Lemon", value: "Lemon" },
    { label: "Lemon mint", value: "Lemon mint" },
    { label: "Lemon tea", value: "Lemon tea" },
    { label: "Mango", value: "Mango" },
    { label: "Margarita", value: "Margarita" },
    { label: "Marlett", value: "Marlett" },
    { label: "Melon blue", value: "Melon blue" },
    { label: "Orange", value: "Orange" },
    { label: "Passion kiss", value: "Passion kiss" },
    { label: "Passionfruit mojito", value: "Passionfruit mojito" },
    { label: "Peaches  cream", value: "Peaches  cream" },
    { label: "Pink", value: "Pink" },
    { label: "Pirates cave", value: "Pirates cave" },
    { label: "Pina colada", value: "Pina colada" },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Pink", value: "Pink" },
    { label: "Pirates cave", value: "Pirates cave" },
    { label: "Plum", value: "Plum" },
    { label: "Pomberry", value: "Pomberry" },
    { label: "Pomegranate", value: "Pomegranate" },
    { label: "Pumpkin pie", value: "Pumpkin pie" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Rose", value: "Rose" },
    { label: "Royal grape", value: "Royal grape" },
    { label: "Safari melon dew", value: "Safari melon dew" },
    { label: "Sex on the beach", value: "Sex on the beach" },
    { label: "Sour apple", value: "Sour apple" },
    { label: "Spearmint", value: "Spearmint" },
    { label: "Spicy red", value: "Spicy red" },
    { label: "Strawberry", value: "Strawberry" },
    { label: "Strawberry daiquiri", value: "Strawberry daiquiri" },
    { label: "Strawberry margarita", value: "Strawberry margarita" },
    { label: "Sweet apple", value: "Sweet apple" },
    { label: "Sweet melon", value: "Sweet melon" },
    { label: "Tangerine dream", value: "Tangerine dream" },
    { label: "Tequila sunrise", value: "Tequila sunrise" },
    { label: "Tropical fruit", value: "Tropical fruit" },
    { label: "Turkish apple", value: "Turkish apple" },
    { label: "Ufo", value: "Ufo" },
    { label: "Vanilla", value: "Vanilla" },
    { label: "Watermelon", value: "Watermelon" },
    { label: "White grape", value: "White grape" },
    { label: "White peach", value: "White peach" },
    { label: "Wild berry", value: "Wild berry" },
    { label: "Wild berry mint", value: "Wild berry mint" },
    { label: "Winterfresh", value: "Winterfresh" },
  ],
  "Starbuzz Bold": [
    { label: "Apple doppio ", value: "Apple doppio " },
    { label: "Apple mist", value: "Apple mist" },
    { label: "Asian persuasion", value: "Asian persuasion" },
    { label: "Black mint", value: "Black mint" },
    { label: "Black peach mist", value: "Black peach mist" },
    { label: "Brownie", value: "Brownie" },
    { label: "Code blue", value: "Code blue" },
    { label: "Cosmo power", value: "Cosmo power" },
    { label: "Dibs on ashley", value: "Dibs on ashley" },
    { label: "French buzz", value: "French buzz" },
    { label: "Geisha", value: "Geisha" },
    { label: "Golden grape", value: "Golden grape" },
    { label: "Grape freeze", value: "Grape freeze" },
    { label: "Grapefruit mint", value: "Grapefruit mint" },
    { label: "Green savior", value: "Green savior" },
    { label: "Irish peach", value: "Irish peach" },
    { label: "Irish kiss", value: "Irish kiss" },
    { label: "Jack the ripper", value: "Jack the ripper" },
    { label: "Lady in red", value: "Lady in red" },
    { label: "Margarita freeze", value: "Margarita freeze" },
    { label: "Mighty freeze", value: "Mighty freeze" },
    { label: "Mint colossus", value: "Mint colossus" },
    { label: "Peach ice tea", value: "Peach ice tea" },
    { label: "Peach mist", value: "Peach mist" },
    { label: "Peach queen", value: "Peach queen" },
    { label: "Pineapple freeze", value: "Pineapple freeze" },
    { label: "Pink lady", value: "Pink lady" },
    { label: "Purple savior", value: "Purple savior" },
    { label: "Queen of sex", value: "Queen of sex" },
    { label: "Simply mango", value: "Simply mango" },
    { label: "Simply mint", value: "Simply mint" },
    { label: "Spiced chai", value: "Spiced chai" },
    { label: "Tropicool", value: "Tropicool" },
    { label: "Watermelon freeze", value: "Watermelon freeze" },
    { label: "White bear", value: "White bear" },
    { label: "White chai", value: "White chai" },
    { label: "White mint", value: "White mint" },
  ],
  "Starbuzz Vintage": [
    { label: "Alaskan freeze", value: "Alaskan freeze" },
    { label: "Colombian spice", value: "Colombian spice" },
    { label: "Dark caribbean", value: "Dark caribbean" },
    { label: "Dark mist", value: "Dark mist" },
    { label: "Dark vanilla", value: "Dark vanilla" },
    { label: "Delhi tea", value: "Delhi tea" },
    { label: "Fresh lime", value: "Fresh lime" },
    { label: "Ginkco", value: "Ginkco" },
    { label: "Honey dew me", value: "Honey dew me" },
    { label: "Indian spiced apple", value: "Indian spiced apple" },
    { label: "Morning breeze", value: "Morning breeze" },
    { label: "Orange chocolate", value: "Orange chocolate" },
    { label: "Peach spice", value: "Peach spice" },
    { label: "Root beer", value: "Root beer" },
    { label: "Shanghai passion", value: "Shanghai passion" },
    { label: "Spice me red", value: "Spice me red" },
    { label: "Sweet cigar", value: "Sweet cigar" },
    { label: "Tiramisu", value: "Tiramisu" },
    { label: "Tokyo spice", value: "Tokyo spice" },
    { label: "White mist", value: "White mist" },
  ],
  "Starbuzz Serpent": [
    { label: "Crimson fox", value: "Crimson fox" },
    { label: "After burner", value: "After burner" },
    { label: "Cobra khan", value: "Cobra khan" },
    { label: "Bohemian", value: "Bohemian" },
    { label: "Crow", value: "Crow" },
    { label: "Gee spot", value: "Gee spot" },
    { label: "Kings tea", value: "Kings tea" },
    { label: "Mad dog", value: "Mad dog" },
    { label: "Lioness", value: "Lioness" },
    { label: "Megawatt", value: "Megawatt" },
    { label: "Rogue", value: "Rogue" },
    { label: "New amsterdam", value: "New amsterdam" },
    { label: "Shishi", value: "Shishi" },
    { label: "Sin city", value: "Sin city" },
    { label: "Skull", value: "Skull" },
    { label: "Sting mint", value: "Sting mint" },
    { label: "Teabet", value: "Teabet" },
    { label: "Kathmandu", value: "Kathmandu" },
  ],
  Tangiers: [
    { label: "Absinthe", value: "Absinthe" },
    { label: "Apple", value: "Apple" },
    { label: "Apricot spring blend", value: "Apricot spring blend" },
    { label: "Aussie juice", value: "Aussie juice" },
    { label: "Blackberry", value: "Blackberry" },
    { label: "Blitzsturm", value: "Blitzsturm" },
    { label: "Blue flower", value: "Blue flower" },
    { label: "Blue gumball 2.0", value: "Blue gumball 2.0" },
    { label: "2005 blueberry", value: "2005 blueberry" },
    { label: "Brambleberry", value: "Brambleberry" },
    { label: "Bug powder", value: "Bug powder" },
    { label: "Cane mint", value: "Cane mint" },
    { label: "Cherry limeade", value: "Cherry limeade" },
    { label: "Chocolate iced cream", value: "Chocolate iced cream" },
    { label: "Chocolate mint", value: "Chocolate mint" },
    { label: "Cocoa", value: "Cocoa" },
    { label: "Coconut", value: "Coconut" },
    { label: "Cool strawberry", value: "Cool strawberry" },
    { label: "Dark cherry", value: "Dark cherry" },
    { label: "Double orange", value: "Double orange" },
    { label: "Experimint", value: "Experimint" },
    { label: "Forbidden fruit", value: "Forbidden fruit" },
    { label: "Foreplay on the peach", value: "Foreplay on the peach" },
    { label: "French jelly", value: "French jelly" },
    { label: "Grapefruit", value: "Grapefruit" },
    { label: "Green apple stuff", value: "Green apple stuff" },
    { label: "Green tea", value: "Green tea" },
    { label: "Guajava", value: "Guajava" },
    { label: "Guanabana", value: "Guanabana" },
    { label: "Hacitragus", value: "Hacitragus" },
    { label: "Horchata", value: "Horchata" },
    { label: "Indian summer", value: "Indian summer" },
    {
      label: "It's like that one breakfast cereal",
      value: "It's like that one breakfast cereal",
    },
    {
      label: "It's like that other breakfast cereal",
      value: "It's like that other breakfast cereal",
    },
    { label: "Jackfruit", value: "Jackfruit" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Kashmir", value: "Kashmir" },
    { label: "Kashmir apple", value: "Kashmir apple" },
    { label: "Kashmir black", value: "Kashmir black" },
    { label: "Kashmir blue", value: "Kashmir blue" },
    { label: "Kashmir cherry", value: "Kashmir cherry" },
    { label: "Kashmir guajava", value: "Kashmir guajava" },
    { label: "Kashmir peach", value: "Kashmir peach" },
    { label: "Kosmik", value: "Kosmik" },
    { label: "Lemon-lime", value: "Lemon-lime" },
    { label: "Lemon", value: "Lemon" },
    { label: "Lemon blossom", value: "Lemon blossom" },
    { label: "Lemon tea", value: "Lemon tea" },
    { label: "Lime", value: "Lime" },
    { label: "Little purple stuff", value: "Little purple stuff" },
    { label: "Mandarin orange", value: "Mandarin orange" },
    { label: "Maraschino cherry", value: "Maraschino cherry" },
    { label: "Marigold", value: "Marigold" },
    { label: "Melon blend", value: "Melon blend" },
    { label: "Mime", value: "Mime" },
    { label: "Mimon", value: "Mimon" },
    { label: "Mixed fruit #6", value: "Mixed fruit #6" },
    { label: "Now with melon", value: "Now with melon" },
    { label: "Old school watermelon", value: "Old school watermelon" },
    { label: "Ololíuqui", value: "Ololíuqui" },
    { label: "Opuntia pear", value: "Opuntia pear" },
    { label: "Orange soda", value: "Orange soda" },
    { label: "Panic punch", value: "Panic punch" },
    { label: "Papaya sorbet", value: "Papaya sorbet" },
    { label: "Passionfruit", value: "Passionfruit" },
    { label: "Peach cobbler", value: "Peach cobbler" },
    { label: "Peach iced tea", value: "Peach iced tea" },
    { label: "Pear-watermelon", value: "Pear-watermelon" },
    { label: "Pear", value: "Pear" },
    { label: "Pikina sun", value: "Pikina sun" },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Pinepas", value: "Pinepas" },
    { label: "Pink grapefruit", value: "Pink grapefruit" },
    { label: "Prince of gray", value: "Prince of gray" },
    { label: "Pumpkin", value: "Pumpkin" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Red tea", value: "Red tea" },
    { label: "Regal flower", value: "Regal flower" },
    { label: "Schnozzberry", value: "Schnozzberry" },
    { label: "Sevilla orange", value: "Sevilla orange" },
    { label: "Sour", value: "Sour" },
    { label: "Sour grape", value: "Sour grape" },
    { label: "Sour watermelon", value: "Sour watermelon" },
    { label: "Static starlight", value: "Static starlight" },
    { label: "Strawberry", value: "Strawberry" },
    { label: "Strawberry-kiwi", value: "Strawberry-kiwi" },
    { label: "Summer resort", value: "Summer resort" },
    {
      label: "Summer solstice celebration",
      value: "Summer solstice celebration",
    },
    { label: "Tasty peach", value: "Tasty peach" },
    { label: "Tropical punch", value: "Tropical punch" },
    { label: "Tropical revenge!", value: "Tropical revenge!" },
    { label: "Tuscan cantaloupe", value: "Tuscan cantaloupe" },
    { label: "Watermelon", value: "Watermelon" },
    { label: "Welsh cream", value: "Welsh cream" },
    { label: "White grape", value: "White grape" },
    { label: "White summer mixed fruit", value: "White summer mixed fruit" },
    { label: "Wintergreen", value: "Wintergreen" },
    { label: "Yunan shaddok", value: "Yunan shaddok" },
  ],
  "Trifecta Dark": [
    {
      label: "Arak / anise spirit (limited)",
      value: "Arak / anise spirit (limited)",
    },
    { label: "Apple pie", value: "Apple pie" },
    { label: "Bdh", value: "Bdh" },
    { label: "Blueberry", value: "Blueberry" },
    { label: "Cherry plum", value: "Cherry plum" },
    { label: "Concord grape", value: "Concord grape" },
    { label: "Cool cinnamon gum", value: "Cool cinnamon gum" },
    { label: "Death by ice", value: "Death by ice" },
    { label: "Deja-dew", value: "Deja-dew" },
    { label: "Durty mint", value: "Durty mint" },
    { label: "Earl grey", value: "Earl grey" },
    { label: "Enigma", value: "Enigma" },
    { label: "Grapefruit", value: "Grapefruit" },
    { label: "Hipster mint", value: "Hipster mint" },
    { label: "Indian kheer", value: "Indian kheer" },
    { label: "Lavender mint", value: "Lavender mint" },
    { label: "Lemon pie", value: "Lemon pie" },
    { label: "Lime", value: "Lime" },
    { label: "Lychee", value: "Lychee" },
    { label: "Manzanas", value: "Manzanas" },
    { label: "Morning glory", value: "Morning glory" },
    { label: "Orange seville coffee", value: "Orange seville coffee" },
    { label: "Pearfect", value: "Pearfect" },
    { label: "Peppermint shake", value: "Peppermint shake" },
    { label: "Pineapple", value: "Pineapple" },
    { label: "Pulp friction", value: "Pulp friction" },
    { label: "Raspberry", value: "Raspberry" },
    { label: "Ruby", value: "Ruby" },
    { label: "Spumoni", value: "Spumoni" },
    { label: "The twist", value: "The twist" },
    { label: "Tko", value: "Tko" },
    { label: "True grape", value: "True grape" },
    { label: "Ventura peach", value: "Ventura peach" },
  ],
  "Trifecta Blonde": [
    { label: "Apple 509", value: "Apple 509" },
    { label: "Bds", value: "Bds" },
    { label: "Blue strawberry", value: "Blue strawberry" },
    { label: "Bohemian mix", value: "Bohemian mix" },
    { label: "Bonafide (banana)", value: "Bonafide (banana)" },
    { label: "Cherry berry", value: "Cherry berry" },
    { label: "Coconut ginger", value: "Coconut ginger" },
    { label: "Cucumber mojito", value: "Cucumber mojito" },
    { label: "Iced orange mint", value: "Iced orange mint" },
    { label: "Lemon mint", value: "Lemon mint" },
    { label: "Huckleberry", value: "Huckleberry" },
    { label: "Mango smoothie (2.0)", value: "Mango smoothie (2.0)" },
    { label: "Mediterranean mint", value: "Mediterranean mint" },
    { label: "Melon melange", value: "Melon melange" },
    { label: "Moro zest", value: "Moro zest" },
    { label: "Mountain fog", value: "Mountain fog" },
    { label: "Nawar", value: "Nawar" },
    { label: "P3", value: "P3" },
    { label: "Peach mint", value: "Peach mint" },
    { label: "Peppermint shake", value: "Peppermint shake" },
    { label: "Pineapple guava", value: "Pineapple guava" },
    { label: "Pumpkin somethin'", value: "Pumpkin somethin'" },
    { label: "Raspberry lemon roll", value: "Raspberry lemon roll" },
    { label: "Spiced java", value: "Spiced java" },
    { label: "Tnt", value: "Tnt" },
    { label: "Twice the ice", value: "Twice the ice" },
    { label: "Twice the ice extreme", value: "Twice the ice extreme" },
    { label: "Vanilla", value: "Vanilla" },
    { label: "Vertigo (the buzz)", value: "Vertigo (the buzz)" },
    { label: "Persian melon", value: "Persian melon" },
  ],
};

export const brandList = [
  "Adalya",
  "Al Fakher",
  "Azure Gold",
  "Azure Black",
  "Chaos",
  "Darkside Base",
  "Darkside Core",
  "Darkside Rare",
  "Element Water",
  "Element Earth",
  "Element Air",
  "Fumari",
  "Holster",
  "MustHave",
  "Starbuzz",
  "Starbuzz Bold",
  "Starbuzz Vintage",
  "Starbuzz Serpent",
  "Tangiers",
  "Trifecta Dark",
  "Trifecta Blonde",
];
